# Generated by Django 4.2.18 on 2025-01-25 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, null=True)),
                ('pub_date', models.DateField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('details', models.TextField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('FICTION', 'Fiction'), ('NON_FICTION', 'Non-fiction'), ('SCIENCE', 'Science'), ('HISTORY', 'History'), ('BIOGRAPHY', 'Biography'), ('REKA', 'Reka')], max_length=100)),
                ('borrowingDate', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userPhoto', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('is_admin', models.BooleanField(default=False)),
                ('book_list', models.ManyToManyField(blank=True, to='workingApp.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
